version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_scavenger_hunt_development
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/ai_scavenger_hunt_development
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
